// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int64
	UserID      int64
	Title       string
	Description string
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    pgtype.Timestamptz
}
